# Generated by Django 6.0.4 on 2026-04-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdmtoken',
            name='hardware_id',
            field=models.CharField(default='LEGACY_DEVICE', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kdmtoken',
            name='max_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='kdmtoken',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theatre',
            name='hardware_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
